# Generated by Django 4.0.4 on 2022-05-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0002_alter_faculty_options_alter_faculty_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sce.faculty')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuela',
                'ordering': ['name'],
            },
        ),
    ]
