# Generated by Django 4.0.4 on 2022-05-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0003_alter_faculty_options_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterField(
            model_name='school',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='sce.faculty'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='sce.school')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
    ]
