# Generated by Django 4.0.4 on 2022-05-27 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sce', '0007_department_created_by_department_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('id_document', models.CharField(max_length=20, verbose_name='Cedula')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='F. Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, verbose_name='Sexo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo(a) ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='F. Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='F. Modificacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_professors', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesors', to='sce.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_professors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'professor',
                'ordering': ['name'],
            },
        ),
    ]
