# Generated by Django 4.0.4 on 2022-05-30 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sce', '0013_alter_department_created_at_alter_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asignature_type', models.CharField(choices=[('M', 'MANDATORY'), ('O', 'OPTIONAL')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_exempt_interships', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asignatures', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatures', to='sce.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_asignatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignature',
                'verbose_name_plural': 'Asignatures',
                'ordering': ['name'],
            },
        ),
    ]
