# Generated by Django 4.0.4 on 2022-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0015_rename_is_exempt_interships_asignature_is_exempted_interships'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignature',
            name='code',
            field=models.CharField(default=0, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
