# Generated by Django 4.0.4 on 2022-07-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0017_alter_asignature_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensumDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('prelated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensum_detail', to='sce.asignature')),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sce.pensum')),
            ],
        ),
    ]
