# Generated by Django 4.0.4 on 2022-07-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0018_pensumdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensumdetail',
            options={'ordering': ['pensum', 'semester', 'id']},
        ),
        migrations.AlterField(
            model_name='pensumdetail',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sce.pensum'),
        ),
        migrations.AlterField(
            model_name='pensumdetail',
            name='semester',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')]),
        ),
    ]
