# Generated by Django 4.0.4 on 2022-07-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0019_alter_pensumdetail_options_alter_pensumdetail_pensum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumdetail',
            name='semester',
            field=models.IntegerField(choices=[[1, 'FIRST'], [2, 'SECOND'], [3, 'THIRD'], [4, 'FOURTH'], [5, 'FIFTH'], [6, 'SIXTH'], [7, 'SEVENTH'], [8, 'EIGHTH'], [9, 'NINETH'], [10, 'TENTH']]),
        ),
    ]
